### PR TITLE
Release/0.10.0

### PR DESCRIPTION
**Pull request by wiverson**
## What kind of change does this PR introduce?

Fixes to support the auth 4.0 release

## What is the current behavior?

Currently relies on the auth 3.x release

## Additional context

Probably should rely on a 4.0.1 cut of auth, if the bug fixes from https://github.com/supabase-community/gotrue-csharp/pull/60 are released this PR probably should be updated to that 4.0.1

### CODE REVIEW

**Comment by acupofjose** [comment]
Waiting to merge `gotrue-csharp@4.x` until I get a releases for `postgrest-csharp@3.2.x` and `realtime-csharp@6.x` done!

**Comment by wiverson** [comment]
Anything I can do to help?  :)

**Comment by wiverson** [comment]
I wound up writing this script to help me sort things out. https://gist.github.com/wiverson/45a370ead1919e9f44ad78ec90a9b8c2

I think I may need to tweak it to use git sparseCheckout so I can get source all in one Unity project w/o pulling in the rest of the repos (e.g. base project modules, examples, etc). Hmm.

**Comment by acupofjose** [comment]
Sure! You're welcome to look at supabase-community/postgrest-csharp#65 or supabase-community/realtime-csharp#28!

That script is really cool - agreed on the sparse checkout, you probably don't want all that extra stuff in there!

**Comment by wiverson** [comment]
FYI took some time to look at postgrest-csharp#65 and looks like it's got two open broken tests. LMK when you get that sorted. I'll take a look at realtime next.

**Comment by wiverson** [comment]
It looks like realtime doesn't have a docker config, the test version is pointed at a live supabase instance is my guess?

**Comment by acupofjose** [comment]
Indeed - I'm working on realtime channels/presence/broadcast right now. The docker setup was unfortunately rather convoluted the last time I tried, so I moved it to a live "testing" instance that's whitelisted for that purpose on supabase's hosted service. Moving it back to local testing is part of this cleanup/refactor!

**Comment by wiverson** [comment]
Cool. I don't know enough about linq to sort out those two broken tests in postgrest w/o a bunch of research (linq isn't used in Unity dev much for a variety of reasons). I really don't want to send in PRs w/o a test suite for realtime. :)

FWIW the changes for the updated auth in the parent supabase client are pretty minor. If you want to kick out an updated version of the parent client that just includes the new auth that would be awesome. Do you think it'll be more than a few days for the postgrest & realtime?

**Comment by acupofjose** [comment]
lol totally understood! I'll take a gander.

It's a breaking API change on how events work, even if they are minor. I suppose they still have _essentially_ the same signatures (at least pretty close)... I could do a v0.10.0 release on these?

**Comment by acupofjose** [comment]
Available in v0.10.0!

**Pull request merged**
